services:
  db:
    container_name: laravelMySQL
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes: 
      - mySql:/var/lib/mysql
    networks:
      - journalObservationAgronomic

  redis:
    container_name: redis
    image: redis:7.0
    ports: 
      - 6377:6380
    command: redis-server --requirepass ${REDIS_PASSWORD} 
    volumes:
      - redis_data:/data
    networks: 
      - journalObservationAgronomic
volumes:
  mySql:
  redis_data:

networks:
  journalObservationAgronomic: